import { WorkflowDetail, WorkflowSummary } from './models';

const ingestFields = [
  {
    key: 'seed_url',
    label: 'Seed URL',
    type: 'url',
    required: true,
    default: 'https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html',
    description: 'Starting page for crawl.',
  },
  {
    key: 'max_tokens',
    label: 'Max tokens per chunk',
    type: 'number',
    required: true,
    default: 400,
    min: 50,
    max: 8000,
  },
  {
    key: 'overlap_tokens',
    label: 'Overlap tokens',
    type: 'number',
    required: true,
    default: 40,
    min: 0,
    max: 2000,
  },
  {
    key: 'max_pages',
    label: 'Max pages',
    type: 'number',
    required: true,
    default: 30,
    min: 1,
    max: 1000,
  },
  {
    key: 'max_depth',
    label: 'Max crawl depth',
    type: 'number',
    required: true,
    default: 2,
    min: 0,
    max: 20,
  },
  {
    key: 'timeout_seconds',
    label: 'Timeout seconds',
    type: 'number',
    required: true,
    default: 20,
    min: 1,
    max: 300,
  },
  {
    key: 'allowed_domains',
    label: 'Allowed domains',
    type: 'textarea-list',
    description: 'One domain per line.',
    default: ['docs.aws.amazon.com'],
  },
  {
    key: 'allowed_path_prefixes',
    label: 'Allowed path prefixes',
    type: 'textarea-list',
    description: 'One path prefix per line.',
    default: ['/bedrock/latest/userguide/'],
  },
  {
    key: 'chunking_methods',
    label: 'Chunking methods',
    type: 'multiselect',
    required: true,
    default: [
      'fixed_token',
      'sliding_window_overlap',
      'sentence',
      'paragraph_section',
      'semantic',
      'hierarchical',
      'query_aware',
    ],
    options: [
      { label: 'Fixed token', value: 'fixed_token' },
      { label: 'Sliding window overlap', value: 'sliding_window_overlap' },
      { label: 'Sentence', value: 'sentence' },
      { label: 'Paragraph section', value: 'paragraph_section' },
      { label: 'Semantic', value: 'semantic' },
      { label: 'Hierarchical', value: 'hierarchical' },
      { label: 'Query aware', value: 'query_aware' },
    ],
  },
  {
    key: 'query_terms',
    label: 'Query terms',
    type: 'textarea-list',
    description: 'One query term per line for query-aware chunking.',
    default: ['knowledge base', 'foundation model', 'guardrails'],
  },
  {
    key: 'fetch_again',
    label: 'Fetch again',
    type: 'checkbox',
    default: false,
    description: 'Ignore latest cache and run a fresh crawl.',
  },
];

export const FALLBACK_WORKFLOWS: WorkflowSummary[] = [
  {
    module: 'ingest',
    workflow_selector: 'ingest/AWSBedrock',
    workflow_parent: 'ingest',
    workflow_child: 'AWSBedrock',
    workflow_id: 'ingest_001',
    display_name: 'AWS Bedrock Docs Ingest',
    short_description: 'Crawl AWS Bedrock docs and create multi-strategy chunked artifacts.',
    last_execution: {
      status: 'Never Executed',
      execution_id: null,
      started_at: null,
      completed_at: null,
    },
  },
];

export const FALLBACK_WORKFLOW_DETAILS: Record<string, WorkflowDetail> = {
  'ingest/AWSBedrock': {
    ...FALLBACK_WORKFLOWS[0],
    title: 'Run AWS Bedrock Ingest Workflow',
    description:
      'Fallback metadata is loaded because API is unavailable. Start the backend to run live workflow operations.',
    fields: ingestFields,
    raw_config: {
      workflow_id: 'ingest_001',
      seed_url: 'https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html',
      max_tokens: 400,
      overlap_tokens: 40,
      max_pages: 30,
      max_depth: 2,
      timeout_seconds: 20,
      allowed_domains: ['docs.aws.amazon.com'],
      allowed_path_prefixes: ['/bedrock/latest/userguide/'],
      query_terms: ['knowledge base', 'foundation model', 'guardrails'],
      chunking_methods: [
        'fixed_token',
        'sliding_window_overlap',
        'sentence',
        'paragraph_section',
        'semantic',
        'hierarchical',
        'query_aware',
      ],
    },
  },
};

